### ISSUE TITLE
Request Noi Ask for Mistral Chat

### ISSUE THREAD

**Issue by ronpay** [lencx/Noi#106]
Noi ask is very helpful to me, I hope to support mistral chat.

There is introduce of Mistral Chat:

Introduction to Mistral Large Model: https://mistral.ai/news/mistral-large/
Mistral Chat Address : https://chat.mistral.ai/chat

Thanks.

**Comment by OnlyAIGC** [comment]
You can add custom links

**Comment by 13IcHBiN** [comment]
guess he means same as in https://github.com/lencx/Noi/issues/103 topic
if you mean custom links then noi ask (when you can write same request in diffetent ai sites via brain button) wouldn't work
of course it is possible to go inside \AppData\Roaming\Noi\extensions\noi-ask\ and edit files with button name etc data from site but it isn't convenient.

Guess one of the ways is add additional logic in the following way:
1. when user added new link he can open link to enter site and login there
2. on the site page where is line for text input and send request button user need to enter site settings via Noi to "Edit site parameter" 
3. There should appears 2 new buttons that write two variables from site 
"text input line"
"enter request"
4. Well, then the user clicks on these buttons and indicates where the line for entering text and the button for sending a request are located, so that, by analogy with capturing an object from, for example, Noi's Inspect Elements or developer tools in Google Chrome, that the data was recorded in variables and recognized for use by Noi questions
5. Sounds simple, all that remains is to figure out how to do it all so that it works and implement it in code))

![image](https://github.com/lencx/Noi/assets/57899499/7f72ba8a-6df6-45ff-8152-297633a5ba6a)

![image](https://github.com/lencx/Noi/assets/57899499/bb984975-b87f-4b1e-9a0d-a21272204c11)


@lencx what you say about that?))

**Comment by lencx** [comment]
@13IcHBiN DOM selectors are not universal. If you look at the source code of `noi-ask`, you'll find that retrieving some input fields requires complex logic, and relying solely on input fields would be very limiting. It's recommended to implement your own logic in `noi-ask-custom` (https://github.com/lencx/Noi/tree/main/extensions/noi-ask-custom). Implementing custom logic in noi-ask could be overwritten by application updates.

**Comment by 13IcHBiN** [comment]
yes, I’ve already poked around there, such additions cause difficulties, by the way I also noticed that if diligently poke around in C:\Users\*username*\AppData\Local\noi\app-0.4.0\resources\extensions\noi-ask-custom then noi will simply be displayed as a white screen at startup, to fix it had to go to C:\Users\*username*\AppData\Roaming\Noi\ to clean it up and fix it

**Comment by ronpay** [comment]
Thank you for your reply, I will try to implement this using noi-ask-custom later.
