### ISSUE TITLE
Extremely laggy

### ISSUE THREAD

**Issue by AspireOne** [lencx/Noi#20]
The app is extremely laggy - both the UI, and loading websites. The concept could be rethinked as a whole - this is just a web wrapper around other websites. The reason I loved the ChatGPT app is that is is fast, clean, quick to pull up, and it feels native. This does not have much benefits.

**Comment by diomonogatari** [comment]
I've been abusing this Noi and even tested opening Teams in it.
It has hold the fort like a champ.

I've played with ChatGPT desktop and Noi and they both feel the same.

My specs:
![image](https://github.com/lencx/Noi/assets/17832206/31b47077-2ca7-4053-a130-716d33092249)

![image](https://github.com/lencx/Noi/assets/17832206/089d9cb5-fa14-491b-8586-e0493be8ced0)


@AspireOne i'm not a contributor here but if you can, please drop your specs so that @lencx can have more info :)

**Comment by lencx** [comment]
The ChatGPT desktop application and Noi represent two distinct architectures. Initially, I opted for Tauri as the packaging solution due to its compact nature. However, later on, numerous issues arose that became unmanageable. For instance, downloading images from web pages became ineffective, and the use of different webview versions across various systems led to many UI vulnerabilities.

Noi's build tool utilizes Electron. Despite its considerable size, it provides a more stable browser API. This allows me to create a wider array of interesting features. Its goal is more akin to a browser that focuses on `AI + System`.

**Comment by hacker-hackman** [comment]
@lencx have you any clue why `Noi` doesn't provide access to ChatGPT website via sshuttle while your `ChatGPT desktop`  does? I described this issue in #161
