### ISSUE TITLE
[Suggestion] Support for Chromium Extensions or add an AdBlocker

### ISSUE THREAD

**Issue by ferivoq** [lencx/Noi#28]
Hey!
I've been using Noi for a bit of time and I really like it.
It's a pretty good software for a dev like me who uses a vscode server.
I would love to use Youtube in it to almost kill all of my browser usage but I would really appricate an adblocker to the app.
And a Chromium Extensions support would be cool too for example vencord for discord.
That's all, I will check out how extension are made for the app too btw so I can do something.

**Comment by lencx** [comment]
Hello, I'm glad you like this application. I will release a plugin management feature in the next version, so users will be able to add plugins themselves. However, since Noi is developed based on Electron (which is a subset of Chrome plugins), you can familiarize yourself with this document first: https://www.electronjs.org/docs/latest/api/extensions

**Comment by lencx** [comment]
Please download the latest version, and then add custom extensions here.

<img width="927" alt="load extension" src="https://github.com/lencx/Noi/assets/16164244/b4531965-5692-47b9-9b93-83f29feb114d">

**Comment by dreinert1** [comment]
@lencx after adding the extension like you describe here, how can I activate/use it?

**Comment by lencx** [comment]
@dreinert1 It is similar to a Chrome extension; after importing, no additional operations are needed. If it does not work, you can try restarting the application.
