### ISSUE TITLE
AI Execution Halts When Switching Models

### ISSUE THREAD

**Issue by Macbit** [lencx/Noi#61]
**Issue**

When switching between AI models (e.g., Gemini/GPT), the running AI process halts and the page refreshes.  This prevents the execution of parallel prompts across different AI models.

**Expected Result**

When switching between AI models, the currently running AI processes should continue executing in the background. This would allow for the seamless submission of the same prompt to multiple AI models in parallel.

**Steps to Reproduce**

1. Open a webpage with multiple AI models available (e.g., Gemini, GPT).
2. Start an AI process (begin a conversation or prompt generation) with one of the AI models.
3. Switch to a different AI model.
4. Observe that the first AI process has stopped running and the page may have refreshed.

Further Explanation
The ability to submit the same prompt to multiple AI models simultaneously is valuable for comparing responses, generating creative variations, and streamlining workflows. This issue creates an unnecessary interruption in that process.

**Comment by lencx** [comment]
https://github.com/lencx/Noi/issues/45
You can try using the Noi Ask mode for your inquiries, which allows for multiple AI requests to be made simultaneously. The issue with refreshing upon switching cannot be resolved at the moment, but it has been incorporated into the development plan to implement functionality similar to browser tabs.

**Comment by Macbit** [comment]
@lencx thanks! I think i found another bug - Noi Ask does not work with Gemini (not typing)

**Comment by lencx** [comment]
This is because when the application was released, the Bard domain existed. However, when the domain was updated, the plugin would no longer work. As I am currently busy developing new features, I haven't written a detailed English repair tutorial. I have written a tutorial in Chinese, which you could try to read using a translation, and perhaps it could help you resolve this issue.
https://mp.weixin.qq.com/s/M6gO6MdK5obCvs2LIBZA3w

**Comment by lencx** [comment]
You can try downloading v0.4.0.
